# BLACKLIST AUCTION INVENTORIES HERE
# blacklist works as follows:
# if you include the word "a" in the blacklist, every inventory with the letter "a" will be blocked.
# because of this, try to be as precise as possible.
# If your inventory contains extra characters, such as "Auction Page 8", simply blacklisting "Auction Page" will block every page
blacklistedinventories: ["&4&lMineXChange", "test inventory"]

canopeninair: true            #false will prevent users from opening shulkerboxes by clicking the air
canopenininventory: true      #false will prevent users from opening shulkerboxes in their inventory
canopeninchests: true         #false will prevent users from opening shulkerboxes in chests
canopeninenderchest: true     #false will prevent users from opening shulkerboxes in enderchests
canopeninbarrels: true        #false will prevent users from opening shulkerboxes in barrels
canplaceshulker: true         #false will prevent users from placing shulkerboxes by accident

#true will prevent users from opening shulkerboxes within 7 seconds of being hit by a player
disable-in-combat: false

defaultname: "&9Shulker Pack"
shiftclicktoopen: false
shulkervolume: 1              #0.1 is quiet, 1 is loud
#shift click to open applies to both ingame and in inventory

open-previous-inventory: false
