blacklistedinventories: ["&4&lMineXChange", "test inventory"]

canopeninair: true            #false will prevent users from opening shulkerboxes by clicking the air
canopenininventory: true      #false will prevent users from opening shulkerboxes in their inventory
canopeninchests: true         #false will prevent users from opening shulkerboxes in chests
canopeninenderchest: true     #false will prevent users from opening shulkerboxes in enderchests
canopeninbarrels: true        #false will prevent users from opening shulkerboxes in barrels
canplaceshulker: true         #false will prevent users from placing shulkerboxes by accident

defaultname: "&9Shulker Pack"
shiftclicktoopen: false
shulkervolume: 1              #0.1 is quiet, 1 is loud
#shift click to open applies to both ingame and in inventory
